const normalize = "/*! normalize.css v8.0.1 | MIT License | github.com/necolas/normalize.css */html{-webkit-text-size-adjust:100%;line-height:1.15}body{margin:0}main{display:block}h1{font-size:2em;margin:.67em 0}hr{box-sizing:content-box;height:0;overflow:visible}pre{font-family:monospace,monospace;font-size:1em}a{background-color:transparent}abbr[title]{border-bottom:none;text-decoration:underline;-webkit-text-decoration:underline dotted;text-decoration:underline dotted}b,strong{font-weight:bolder}code,kbd,samp{font-family:monospace,monospace;font-size:1em}small{font-size:80%}sub,sup{font-size:75%;line-height:0;position:relative;vertical-align:baseline}sub{bottom:-.25em}sup{top:-.5em}img{border-style:none}button,input,optgroup,select,textarea{font-family:inherit;font-size:100%;line-height:1.15;margin:0}button,input{overflow:visible}button,select{text-transform:none}[type=button],[type=reset],[type=submit],button{-webkit-appearance:button}[type=button]::-moz-focus-inner,[type=reset]::-moz-focus-inner,[type=submit]::-moz-focus-inner,button::-moz-focus-inner{border-style:none;padding:0}[type=button]:-moz-focusring,[type=reset]:-moz-focusring,[type=submit]:-moz-focusring,button:-moz-focusring{outline:1px dotted ButtonText}fieldset{padding:.35em .75em .625em}legend{box-sizing:border-box;color:inherit;display:table;max-width:100%;padding:0;white-space:normal}progress{vertical-align:baseline}textarea{overflow:auto}[type=checkbox],[type=radio]{box-sizing:border-box;padding:0}[type=number]::-webkit-inner-spin-button,[type=number]::-webkit-outer-spin-button{height:auto}[type=search]{-webkit-appearance:textfield;outline-offset:-2px}[type=search]::-webkit-search-decoration{-webkit-appearance:none}::-webkit-file-upload-button{-webkit-appearance:button;font:inherit}details{display:block}summary{display:list-item}[hidden],template{display:none}";

const HeroBig_vue_vue_type_style_index_0_scoped_aced8b57_lang = '@import url("https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap");.hero[data-v-aced8b57]{height:100vh;position:relative;width:100%}.hero video[data-v-aced8b57]{height:100%;-o-object-fit:cover;object-fit:cover;width:100%}.container[data-v-aced8b57]{bottom:0;display:flex;flex-direction:column;justify-content:center;left:50%;position:absolute;top:0;transform:translateX(-50%)}.texts[data-v-aced8b57]{color:#fff;max-width:680px}h1[data-v-aced8b57]{font-size:62px;line-height:82px;margin-bottom:20px}h2[data-v-aced8b57]{font-size:1.5rem;line-height:1.6666666667em}.scroll[data-v-aced8b57]{bottom:2rem;left:0;position:absolute}.scroll a[data-v-aced8b57]{color:#fff}.scroll span[data-v-aced8b57]{display:inline-block;left:0;position:absolute;top:16px;transform:rotate(-90deg)}';

const ReferenceGrid_vue_vue_type_style_index_0_scoped_a37a7080_lang = '@import url("https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap");.reference-grid[data-v-a37a7080]{display:grid;gap:20px;grid-template-columns:repeat(auto-fill,minmax(320px,1fr));margin:60px 0}.item[data-v-a37a7080]{aspect-ratio:1;overflow:hidden;position:relative}.item img[data-v-a37a7080]{display:block}.item.large[data-v-a37a7080]{grid-column-end:span 2;grid-row-end:span 2}.item .bg-img[data-v-a37a7080]{filter:grayscale(.5);height:100%;-o-object-fit:cover;object-fit:cover;transition:all .2s ease-in-out;width:100%}.item .logo[data-v-a37a7080]{left:50%;max-width:70%;position:absolute;top:50%;transform:translate(-50%,-50%);transition:all .3s ease-in-out;z-index:1}.item .logo img[data-v-a37a7080]{width:100%}.item[data-v-a37a7080]:after{background-color:rgba(0,0,0,.2);content:"";display:block;height:100%;left:0;position:absolute;top:0;transition:all .2s ease-in-out;width:100%}.item:focus .bg-img[data-v-a37a7080],.item:hover .bg-img[data-v-a37a7080]{filter:none;transform:scale(1.1)}.item:focus .logo[data-v-a37a7080],.item:hover .logo[data-v-a37a7080]{opacity:0;transform:translate(-50%,-50%) scale(.7)}';

const BtnSecondary_vue_vue_type_style_index_0_scoped_c38e610b_lang = '@import url("https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap");.btn-secondary[data-v-c38e610b]{color:#222e27;display:inline-block;padding:.625em 1.25em .625em 57px;position:relative;text-decoration:none}.btn-secondary[data-v-c38e610b]:before{background-color:#222e27;content:"";height:42px;left:0;width:42px}.btn-secondary[data-v-c38e610b]:after,.btn-secondary[data-v-c38e610b]:before{display:inline-block;position:absolute;top:50%;transform:translateY(-50%)}.btn-secondary[data-v-c38e610b]:after{content:url(' + globalThis.__publicAssetsURL("img/icon/btn-arrow.svg") + ");left:11px;line-height:0}.btn-secondary[data-v-c38e610b]:focus,.btn-secondary[data-v-c38e610b]:hover{text-decoration:underline}.btn-secondary[data-v-c38e610b]:focus:after,.btn-secondary[data-v-c38e610b]:hover:after{animation:slideArrow-c38e610b .3s ease-in-out}@keyframes slideArrow-c38e610b{0%{transform:translateY(-50%)}50%{transform:translateY(-50%) translateX(30px)}51%{opacity:0;transform:scale(0)}52%{transform:translateY(-50%) translateX(-30px)}to{transform:translateY(-50%)}}";

const SluzbyBlock_vue_vue_type_style_index_0_scoped_334e2deb_lang = '@import url("https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap");.sluzby-wrapper[data-v-334e2deb]{display:flex;gap:50px;margin:60px 0}.sluzby-wrapper>div[data-v-334e2deb]{flex:0 1 50%;width:50%}.sluzby-wrapper .option[data-v-334e2deb]{cursor:pointer}.image-wrapper[data-v-334e2deb]{position:relative}.image-wrapper>div[data-v-334e2deb]{height:100%}.bg-img[data-v-334e2deb],.bg-img[data-v-334e2deb]:before{height:100%;left:0;position:absolute;top:0;width:100%}.bg-img[data-v-334e2deb]:before{background-color:rgba(0,0,0,.4);content:"";display:block}.texts[data-v-334e2deb]{color:#fff;display:flex;flex-direction:column;height:100%;justify-content:center;line-height:1.5em;padding:100px;position:relative;z-index:2}.hashtags[data-v-334e2deb]{display:flex;flex-wrap:wrap;gap:10px}.hashtags span[data-v-334e2deb]{border:1px solid #fff;display:inline-block;padding:.625em 1.25em}.hashtags span[data-v-334e2deb]:before{content:"#";margin-right:.2em}.options-wrapper[data-v-334e2deb]{display:flex;flex-direction:column;justify-content:center}.option[data-v-334e2deb]{padding:20px 0}.option[data-v-334e2deb]:not(:last-of-type){border-bottom:1px solid #b7b7b7}.option h3[data-v-334e2deb]{font-size:3rem;margin:0;transition:all .2s ease-in-out}.option small[data-v-334e2deb]{display:block;font-size:1rem;font-weight:400}.option:focus h3[data-v-334e2deb],.option:hover h3[data-v-334e2deb]{color:#59dc8e}';

const MainHeader_vue_vue_type_style_index_0_scoped_525f9bc1_lang = '@import url("https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap");header[data-v-525f9bc1]{align-items:center;display:flex;left:0;padding:70px;position:absolute;right:0;top:0;z-index:1000}header a[data-v-525f9bc1]{color:#fff;display:inline-block;text-decoration:none}.logo svg[data-v-525f9bc1]{fill:#fff}nav[data-v-525f9bc1]{margin-left:auto}nav ul[data-v-525f9bc1]{display:flex;list-style:none;margin:0;padding:0}nav ul a[data-v-525f9bc1]{border:1px solid transparent;padding:.9375em}nav ul a[data-v-525f9bc1]:focus,nav ul a[data-v-525f9bc1]:hover{border-color:#59dc8e;box-shadow:0 0 15px rgba(89,220,142,.3);color:#59dc8e}.contacts[data-v-525f9bc1]{border-left:2px solid #59dc8e;margin-left:20px;padding-left:20px;position:relative}.contacts a[data-v-525f9bc1]{display:block;line-height:1.4em}.contacts .project-phone[data-v-525f9bc1]{align-items:center;display:flex;font-weight:700}.contacts .project-mail[data-v-525f9bc1]{padding-left:38px}.status[data-v-525f9bc1]{background:radial-gradient(50% 50% at 50% 50%,#a5ff96 0,#59dc8e 100%);border:3px solid #fff;border-radius:50%;box-shadow:0 0 20px #fff;display:inline-block;height:26px;left:20px;margin-right:10px;top:0;width:26px}';

const app_vue_vue_type_style_index_0_lang = '@import url("https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap");*,:after,:before{box-sizing:border-box}html{scroll-behavior:smooth}body{color:#222e27;font-family:Poppins,sans-serif}section{margin-bottom:100px}a{transition:all .3s ease-in-out}.container{margin-left:auto;margin-right:auto;max-width:calc(1440px + 4rem);padding-left:2rem;padding-right:2rem;width:100%}.narrow{max-width:900px;padding-left:0;padding-right:0}.narrow p{line-height:1.8em}.text-center{text-align:center}h2,h3{line-height:1.5em}h2{font-size:3rem}.buttons-center{gap:20px;justify-content:center}.buttons-center,.columns{display:flex;flex-wrap:wrap}.columns.align-center{align-items:center}.columns.col-4-6 .column:first-of-type{flex:1 1 300px}.columns.col-4-6 .column:last-of-type{flex:1 1 500px}';

const interopDefault = r => r.default || r || [];
const styles = {
  entry: () => [normalize, HeroBig_vue_vue_type_style_index_0_scoped_aced8b57_lang, ReferenceGrid_vue_vue_type_style_index_0_scoped_a37a7080_lang, BtnSecondary_vue_vue_type_style_index_0_scoped_c38e610b_lang, SluzbyBlock_vue_vue_type_style_index_0_scoped_334e2deb_lang, MainHeader_vue_vue_type_style_index_0_scoped_525f9bc1_lang, app_vue_vue_type_style_index_0_lang],
  "app.vue": () => import('./_nuxt/app-styles.c9435e8a.mjs').then(interopDefault),
  "components/MainHeader.vue": () => import('./_nuxt/MainHeader-styles.c8456859.mjs').then(interopDefault),
  "pages/index.vue": () => import('./_nuxt/index-styles.cdd0afce.mjs').then(interopDefault),
  "node_modules/@nuxt/ui-templates/dist/templates/error-404.vue": () => import('./_nuxt/error-404-styles.3db9fdd2.mjs').then(interopDefault),
  "node_modules/@nuxt/ui-templates/dist/templates/error-500.vue": () => import('./_nuxt/error-500-styles.ad145178.mjs').then(interopDefault),
  "components/HeroBig.vue": () => import('./_nuxt/HeroBig-styles.a8148c14.mjs').then(interopDefault),
  "components/ReferenceGrid.vue": () => import('./_nuxt/ReferenceGrid-styles.b54b972f.mjs').then(interopDefault),
  "components/SluzbyBlock.vue": () => import('./_nuxt/SluzbyBlock-styles.149a1709.mjs').then(interopDefault),
  "components/BtnSecondary.vue": () => import('./_nuxt/BtnSecondary-styles.852d66c3.mjs').then(interopDefault)
};

const styles$1 = /*#__PURE__*/Object.freeze({
  __proto__: null,
  'default': styles
});

export { BtnSecondary_vue_vue_type_style_index_0_scoped_c38e610b_lang as B, HeroBig_vue_vue_type_style_index_0_scoped_aced8b57_lang as H, MainHeader_vue_vue_type_style_index_0_scoped_525f9bc1_lang as M, ReferenceGrid_vue_vue_type_style_index_0_scoped_a37a7080_lang as R, SluzbyBlock_vue_vue_type_style_index_0_scoped_334e2deb_lang as S, app_vue_vue_type_style_index_0_lang as a, styles$1 as s };
//# sourceMappingURL=styles.mjs.map
